### ISSUE TITLE
Excessive saturation on man meat

### ISSUE THREAD

**Issue by Lykrast** [Akrivus/Revolution#2]
Man meat gives excessive saturation compared to vanilla foods. Viewed with the help of Apple Skin:

![image](https://user-images.githubusercontent.com/8684850/43290080-31e6bc6e-912d-11e8-9bf8-b63096ec606a.png)
![image](https://user-images.githubusercontent.com/8684850/43290089-36b30464-912d-11e8-98e7-d5d40329f0e0.png)

Beef for comparaison:
![image](https://user-images.githubusercontent.com/8684850/43290098-40708526-912d-11e8-98c8-f00c286c54d2.png)

You can view the saturation of vanilla foods where they are created in the Item class. Steak is around 0.8 for example.

**Comment by Akrivus** [comment]
Fixed and will include in next release.
