### ISSUE TITLE
Human shadows too small

### ISSUE THREAD

**Issue by Lykrast** [Akrivus/Revolution#3]
![image](https://user-images.githubusercontent.com/8684850/43290379-3a8a7512-912e-11e8-8b52-1607cf47e1a1.png)

As seen here, the humans have unusually small shadows compared to other humanoid mobs or players:

![image](https://user-images.githubusercontent.com/8684850/43290422-5632d0b6-912e-11e8-8b53-a285f8072def.png)

**Comment by Akrivus** [comment]
Fixed and will include in next release.
