### ISSUE TITLE
Trees from Dynamic Trees are not recognized by NPCs in this mod as valid trees

### ISSUE THREAD

**Issue by Sunconure11** [Akrivus/Revolution#7]
As a result, they basically do... nothing in a world with such a mod.

https://minecraft.curseforge.com/projects/dynamictrees

**Comment by Sunconure11** [comment]
Another side note is that they should figure out how to use mods like Adventurer's Toolbox and Tinker's Construct to an extent.

**Comment by Akrivus** [comment]
The AI is designed to program itself in those instances, I try to keep a hands off approach. The problem with that is an utter lack of consistency. I had one world where humans immediately picked up on farming and had settled down within minutes, while others remained nomadic for weeks.
